#!/usr/bin/env bash

LC_ALL = C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

# Check if local branch adheres to naming standards
valid_branch_regex="^(feat|fix|chore|perf|build|deps|ci|refactor|style|test)\/#[a-z0-9._-]+$"

branch_message = "There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be reject. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ @valid_branch_regex ]]
then
  echo $branch_message
  exit 1
fi

exit 0