name: Package
inputs:
  github_token:
    description: "GitHub token with package credentials"
    required: true
  github_user:
    description: "GitHub user with package credentials"
    required: true
  mvn_central_user:
    description: "Maven Central username"
    required: true
  mvn_central_password:
    description: "Maven Central password"
    required: true
  gpg_signing_key:
    description: "GPG signing key"
    required: true
  gpg_signing_key_password:
    description: "GPG signing key password"
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOL
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ inputs.github_user }}</username>
              <password>${{ inputs.github_token }}</password>
            </server>
            <server>
              <id>ossrh</id>
              <username>${{ inputs.mvn_central_user }}</username>
              <password>${{ inputs.mvn_central_password }}</password>
            </server>
            <server>
              <id>gpg.passphrase</id>
              <password>${{inputs.gpg_signing_key_password}}</password>
            </server>
          </servers>
        </settings>
        EOL
      shell: bash

    - id: print-settings
      name: Print all settings
      run: |
        cat ~/.m2/settings.xml
      shell: bash

    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ inputs.gpg_signing_key }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG
      shell: bash

    - name: Publish to GitHub Packages
      run: mvn -B deploy -P github
      shell: bash