name: Package
inputs:
  github_token:
    description: "GitHub token with package credentials"
    required: true
  github_user:
    description: "GitHub user with package credentials"
    required: true
  mvn_central_user:
    description: "Maven Central username"
    required: true
  mvn_central_password:
    description: "Maven Central password"
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOL
        <settings>
          <activeProfiles>
            <activeProfile>github</activeProfile>
            <activeProfile>maven-central</activeProfile>
          </activeProfiles>
          <servers>
            <server>
              <id>github</id>
              <username>${{ inputs.github_user }}</username>
              <password>${{ inputs.github_token }}</password>
            </server>
            <server>
              <id>ossrh</id>
              <username>${{ inputs.maven_user }}</username>
              <password>${{ inputs.maven_password }}</password>
            </server>
          </servers>
        </settings>
        EOL
      shell: bash

    - name: Publish to GitHub Packages
      run: mvn -B deploy -P github
      shell: bash

    - name: Publish to Maven Central
      run: mvn -B deploy
      shell: bash
