name: "Lint and Test"
description: "Runs linting and tests"
inputs:
  java-version:
    description: "Java version"
    required: false
    default: "11"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ inputs.java-version }}
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B install --file pom.xml
      shell: bash
