name: PR

on:
  push:
    branches-ignore:
      - "main"
      - "master"

permissions:
  contents: read

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom lint-and-test action
        uses: ./.github/actions/lint-and-test
        with:
          java-version: ${{ matrix.java }}
